### PR TITLE
Add actionTaxManager hook

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Add actionTaxManager hook
| Fixed ticket? | none

### CODE REVIEW

**Review by thomasnares — APPROVED** [review]
Thanks @jf-viguier, was it clear on how to create the yaml metadatas ?

**Comment by jf-viguier** [comment]
@thomasnares no, i've just copied another hook !

**Comment by thomasnares** [comment]
Ok, i added a summary here: https://github.com/PrestaShop/docs#maintaining-hook-list-referential
But i think it should be more visible

**Review by matthieu-rolland — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
thanks @jf-viguier

**Pull request merged**
