### PR TITLE
Added troubleshoot documentation

### PR DESCRIPTION
**Pull request by maldarol**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Described a problem’s solution which can occur when there is no json file for the npm build.
| Fixed ticket? | Fixes https://github.com/PrestaShop/example-modules/issues/72

### CODE REVIEW

**Comment by matks** [comment]
Hello,

I have modified your PR to target the `1.7.x` branch.

We have modified the devdocs inner working in order to welcome multiple documentation versions. This is because soon we will have a 1.7 documentation and a 8.0 documentation, matching PrestaShop 1.7 or PrestaShop 8.0 softwares.

Read more on https://devdocs.prestashop.com/1.7/contribute/documentation/how/documentation-versions/

Please also note that now that we have multiple versions inside one documentation, we had to build a workflow that can handle this setup. This repository https://github.com/PrestaShop/docs now only contains the content of the documentation, and https://github.com/PrestaShop/devdocs-site contains the sources and the deployment workflow.

**Comment by maldarol** [comment]
Thank you for the help! Is there anything I should do other than resolving the conflict?

**Comment by matks** [comment]
Hello again ! Sorry for late answer.

I fail to understand why someone would work with PrestaShop's production release 😅  ?

- if you want to contribute to https://github.com/prestashop/prestashop you will use the sources
- if you are building a module or a theme, you do not need to compile assets?

Why do you need to compile assets in your case 🤔  ? Assets are built for the ZIP shipped to production, and are not meant to be modified afterwards ?

**Comment by maldarol** [comment]
I created this PR because I needed to compile assets for my module because the grid I created for it did not worked (the Javascript needed for the row actions was missing). With the production release the compiling always failed with an error.

Maybe there is a better way to include js files to a module but I found this solution. I was thinking that someone else might run into this so it would be good if there was documentation about it.

**Review by matks — CHANGES_REQUESTED** [review]
Sorry for late answer. I think this should rather go in Frequently Asked Questions https://devdocs.prestashop.com/1.7/faq/ not in this part because this is not a standard use of PrestaShop.

**Comment by matks** [comment]
I think this PR is stale so I close it. As the contribution was interesting I ported it to PR https://github.com/PrestaShop/docs/pull/1247

**Pull request closed without merging**
