### PR TITLE
Document configuration console command

### PR DESCRIPTION
**Pull request by tswfi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Add documentation about configuration console command
| Fixed ticket? | 

Document the new configuration console command which was merged here: https://github.com/PrestaShop/PrestaShop/pull/26183 

Replaces #1178 as rebase took way too long :)

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Looks good to me. We could also add it here: https://devdocs.prestashop.com/1.7/development/components/console/

What do you think ? We add the informations to the 2 locations? Only one?

**Comment by tswfi** [comment]
hmm, that page looks like something that should be automated.. 

github action that checks for merges to core
runs --help for all prestashop commands (can these be identified somehow?)
checks the result against the current documentation
if there are differences create a new pr to documentation "Changes to commands documentation found, requires human to review"

It should probably also understand the situation where the human review was not approved so it should check for documentation pr:s for that command and if there are closed pr:s that have not been merged not open a new one..

or something :)

**Comment by matks** [comment]
> hmm, that page looks like something that should be automated..
> 
> github action that checks for merges to core runs --help for all prestashop commands (can these be identified somehow?) checks the result against the current documentation if there are differences create a new pr to documentation "Changes to commands documentation found, requires human to review"

Maybe this would be overkill 😅 ? I'm worried if we build this, we would spend more time fixing the CI and edge cases than the time we would need to write the doc manually

https://xkcd.com/974/

**Comment by tswfi** [comment]
Maybe :D

https://xkcd.com/1205/

**Review by matthieu-rolland — COMMENTED** [review]
I agree that it would make sense to have it in the console page too 👍

**Comment by tswfi** [comment]
Yup, now I had some free time to set up a local devdocs site so that I can see what I'm doing :D

**Comment by tswfi** [comment]
Still think it might be worth it to write a script that could build the "base" for each cli command :)

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @tswfi

**Pull request merged**
