### PR TITLE
Add basic carrier module doc

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Doc ported from: http://doc.prestashop.com/display/PS16/Creating+a+carrier+module

### CODE REVIEW

**Review by PululuK — APPROVED** [review]

**Comment by okom3pom** [comment]
Hello @eternoendless 

What do you think to add a notice for the `id_reference` it's usefull when we edit a carrier, i found this long time ago in a book.

9782212141924_internet_w290

**Comment by eternoendless** [comment]
@okom3pom I just ported the old docs, I'm not that familiar with carrier modules myself. All specific contributions are welcome!

**Comment by okom3pom** [comment]
I am not ready to put suggest change i need to know how it's work when the PR is merged i add a contribution about that

**Review by ghost — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @eternoendless

**Pull request merged**
