### PR TITLE
Update native modules for 8.0.0

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Update modules that become Native in 8.0.0
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

### CODE REVIEW

**Comment by kpodemski** [comment]
Hey @leemyongpakvn 

I'm not sure about some of the modules that you marked as a non-native for 1.7, for example:
[ps_specials](https://github.com/PrestaShop/ps_specials)
[ps_supplierlist](https://github.com/PrestaShop/ps_supplierlist)
[ps_cashondelivery](https://github.com/PrestaShop/ps_cashondelivery)
or even [ps_googleanalytics](https://github.com/PrestaShop/ps_googleanalytics)

and there's more, basically, every module that has min compat 1.7 is a native module, right?

**Comment by leemyongpakvn** [comment]
@kpodemski If you check [File changed](https://github.com/PrestaShop/docs/pull/1651/files#diff-b4283742cedc656c722b58fe19d201ab22fb03c6bf70d3a6802d404d822c3606R89-R130), you will see these 4 modules were marked as non Native in 1.7 by other contributor. I did not change any value in `Native in 1.7` column.
Be free to suggest change if you are sure they are Native in 1.7 ;)

**Comment by leemyongpakvn** [comment]
FYI, I see [ps_cashondelivery.yml](https://github.com/PrestaShop/native-modules/commits/main/ps_cashondelivery.yml) and [ps_googleanalytics.yml](https://github.com/PrestaShop/native-modules/commits/main/ps_googleanalytics.yml) were added to native-modules by @atomiix on Apr 7, 2022. They are not in [List of native modules](https://github.com/PrestaShop/docs/pull/1651/files#diff-b4283742cedc656c722b58fe19d201ab22fb03c6bf70d3a6802d404d822c3606L12-L52) either.
PS 8.0.0 was released on Oct 26, 2022 so I thought these 10 modules become native since 8.0.0. Maybe PS 1.7.8.6 (May 16, 2022) is the correct version.

**Comment by kpodemski** [comment]
I'll consult this with other maintainers and get back to you @leemyongpakvn

**Comment by kpodemski** [comment]
@leemyongpakvn 

I think we need to rework this page so it's relevant for v8

- Realistically speaking all the modules you added are native since 1.7 :-)
- You can find the entire list of native modules here: https://github.com/PrestaShop/native-modules. You can add missing ones, like `ps_distributionapi`
- Module name changes since 1.6 is not that relevant for v8 and it doesn't make sense to keep it in 1.7 docs and v8 docs. Let's remove everything but the heading and link to the old docs: https://devdocs.prestashop-project.org/1.7/development/native-modules/

**Comment by kpodemski** [comment]
@leemyongpakvn I don't want to add more work for you, I appreciate you noticed that there are some changes to be made there, we can take over next week, just let us know :-)

**Comment by leemyongpakvn** [comment]
Alright. @thomasnares can cover this issue ;)

**Comment by kpodemski** [comment]
@leemyongpakvn  I'll do it myself, I can continue in this PR :)

**Pull request closed without merging**
