### PR TITLE
Refer to versions table of nodejs inside getting started

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | This part was out of date and now refer to the compatibility table of nodejs

### CODE REVIEW

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
The current ref is not found:
> ERROR 2021/12/16 10:12:14 [en] REF_NOT_FOUND: Ref "/1.7/development/compile-assets/": "/home/runner/work/docs/docs/src/content/1.7/themes/getting-started/tools-for-theme-designers.md:173:66": page not found

**Comment by NeOMakinG** [comment]
> The current ref is not found:
> 
> > ERROR 2021/12/16 10:12:14 [en] REF_NOT_FOUND: Ref "/1.7/development/compile-assets/": "/home/runner/work/docs/docs/src/content/1.7/themes/getting-started/tools-for-theme-designers.md:173:66": page not found

Fixed

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @NeOMakinG

**Comment by Progi1984** [comment]
@NeOMakinG Could you backport it to `8;x` branch ?

**Comment by NeOMakinG** [comment]
> @NeOMakinG Could you backport it to `8;x` branch ?

Already done but WIP because of a PR to be compatible with node 16

**Comment by Progi1984** [comment]
Refers to #1254

**Pull request merged**
