### PR TITLE
Adds an example to override a front/admin controller inside a module

### PR DESCRIPTION
**Pull request by WebHelpersPau**
Adds controller documentation

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x & 8.x
| Description?  | Adds an example to override a front/admin controller inside a module
| Fixed ticket? | N/A

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Hi @WebHelpersPau thanks ! looks good to me

But I'm not the best when it comes about module development so I ask for a 2nd review of @kpodemski

**Comment by WebHelpersPau** [comment]
Thanks for your help anyway @matks ;)

**Review by kpodemski — APPROVED** [review]

**Comment by matks** [comment]
Thank you @WebHelpersPau

**Comment by matks** [comment]
@WebHelpersPau Could you submit a PR for branch 8.x ? 😉

**Comment by WebHelpersPau** [comment]
> @WebHelpersPau Could you submit a PR for branch 8.x ? 😉

He it is, https://github.com/PrestaShop/docs/pull/1245

**Comment by SharakPL** [comment]
Is there any way to make override be applied on module install? Like I would have *override/classes/Product.php * inside my module package and when I install it in admin panel it is automatically moved to proper shop location.

**Comment by kpodemski** [comment]
@SharakPL this is how it works right now, overrides are automatically installed during the installation if you have them in: `modules/your_module/override`

**Comment by SharakPL** [comment]
Of course! My mistake. I was actually thinking about applying overrides on theme installation, not the module, because it doesn't seem to work the same way.

**Comment by kpodemski** [comment]
@SharakPL you can have some base module as the dependency of your theme with the overrides that you want to install :-)

**Comment by SharakPL** [comment]
Nice workaround. Thanks!

**Pull request merged**
