### PR TITLE
Fix minor typo for MySQL and wording interrogation

### PR DESCRIPTION
**Pull request by thomasnares**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Fix a typo for mysql and interrogation on wording

### CODE REVIEW

**Review by thomasnares — COMMENTED** [review]
on line 56, not sure about "of its choosing"

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
@thomasnares 

line 56 looks ok,  but it should probably say `ps_facetedsearch`, not `blocklayered` (this is the name of the previous version of the module, which is no longer supported)

feel free to add this change to your task list/roadmap :)

**Comment by eternoendless** [comment]
Does this need to be backported?

**Comment by thomasnares** [comment]
> Does this need to be backported?

already backported

**Pull request merged**
