### PR TITLE
Update CQRS documentation

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Update CQRS documentation
| Fixed ticket? | https://github.com/PrestaShop/PrestaShop/issues/32733

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Review by kpodemski — DISMISSED** [review]
I need some information. Is every single command from this list available in 8.0, or some are available in 8.0 and only some in 8.1?

**Comment by mflasquin** [comment]
> I need some information. Is every single command from this list available in 8.0, or some are available in 8.0 and only some in 8.1?

The main category is '8' so I thought I'd put it all in.

**Comment by matks** [comment]
@kpodemski @mflasquin The `8.x` branch will contain both doc for 8.1 and 8.0

However it is important to make clear what part of the doc are 8.0 only or 8.1 only .

See for example this page https://devdocs.prestashop-project.org/8/modules/concepts/doctrine/ : it's in 1.7.x branch but it only applies for versions higher than 1.7.6 . However it's written clearly to make sure we don't confuse people.

**Comment by thomasnares** [comment]
Can you patch the DocToolsBundle to add a mention when a command was introduced in 8.1 ? 
With : `{{< minver v="8.1.0" >}}` in the markdown.

**Comment by mflasquin** [comment]
Hi @thomasnares @kpodemski , yes I will update the doc generation tool to add automatically a tag with the branch

**Comment by mflasquin** [comment]
Updated @kpodemski @thomasnares 

https://github.com/PrestaShop/docs/pull/1678/files#diff-ad35d1d9189819c2266f216d8de154dab23686cd69a3095191d00e3e2c3a224dR10

**Review by tleon — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
thanks @mflasquin

**Pull request merged**
