### PR TITLE
Update mobile action

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | According to this Pull Request (https://github.com/PrestaShop/PrestaShop/pull/27527), action are changed.

### CODE REVIEW

**Comment by PrestaEdit** [comment]
NOTE: The Pull Request is not merged at this time.
Need to wait the merge.

**Review by PierreRambaud — APPROVED** [review]

**Review by saulaski — APPROVED** [review]

**Review by NeOMakinG — CHANGES_REQUESTED** [review]
Just so it doesn't get merged by mistake until the PR is merged 👍

**Review by Progi1984 — APPROVED** [review]

**Review by Progi1984 — CHANGES_REQUESTED** [review]
Needs a rebase

**Comment by matks** [comment]
PR https://github.com/PrestaShop/PrestaShop/pull/27527 merged

@PrestaEdit if you rebase we can merge this :)

**Comment by PrestaEdit** [comment]
Ou pas. Bordel...

**Pull request closed without merging**
