### PR TITLE
Module / theme functional checklist 1.7.x

### PR DESCRIPTION
**Pull request by mariem-abid**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | Improve the **validation process** of the modules and themes on the **Disneystore**. The requests of "Sarah-Jane Le Corre" (Head of the care team)
| Fixed ticket? | No

cherry-pick: https://github.com/PrestaShop/docs/pull/1368

### CODE REVIEW

**Comment by matthieu-rolland** [comment]
I'm not sure the addon marketplace is in the perimeter of the dev doc.

In the mean time there are some things in your PR that are indeed interesting when it comes to module development best practices 👍 

I'm not sure if we should remove everything that is specific to the addon marketplace, or create a section dedicated to it in the dev doc 🤔 

I'd say it goes against the split open source principle...

@PrestaShop/prestashop-core-developers wdyt ?

**Comment by Thymotep** [comment]
Hello :)

The technical part concerning the creation of the modules being on the devdoc, having a section specific to the Addons rules next to it would be convenient for the editors wishing to submit their module in our eco-system.

As I don't currently have a real documentation platform outside of devdoc, and until we have that, I agree with @matthieu-rolland [matthieu-rolland](https://github.com/matthieu-rolland).

**Comment by matks** [comment]
Hi @Thymotep

- the devdocs must be neutral, so I think we cannot insert content related to PrestaShop SA in it
- however I understand that some people might search for Addons content on the devdocs, because for years the content was stored there

Both decisions (adding content related to Addons or adding a link to this content) are decisions that need to be done by PrestaShop Steering Committee, not me. I think you should reach out to @fabienvallon , @eternoendless or @ttoine about that 😉

**Review by matks — CHANGES_REQUESTED** [review]
Blocked while waiting for Steering Committee decision

https://github.com/PrestaShop/docs/pull/1369#issuecomment-1114640784

**Comment by Progi1984** [comment]
@matks For the community, please explain what is the Steering Committee ?

**Comment by matks** [comment]
@Progi1984 See `Self-appointing council or board` in https://www.redhat.com/en/blog/understanding-open-source-governance-models

**Comment by Progi1984** [comment]
@matks Yes but we don't have any informations about in prestashop project website.

**Comment by matks** [comment]
@Progi1984 I think you should contact @ttoine about this 😉

**Comment by matks** [comment]
@Progi1984 Added an issue about this https://github.com/PrestaShop/open-source/issues/94

**Comment by eternoendless** [comment]
I'm sorry @mariem-abid & @Thymotep but this is way too specific to the PrestaShop SA validation process to be in the project's Devdocs.

Have you considered [public Notion pages](https://www.notion.so/help/public-pages-and-web-publishing)?

**Pull request closed without merging**
