### PR TITLE
Update npm versions needed

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | We need to set this to the doc so we don't have package locks issues

### CODE REVIEW

**Comment by kpodemski** [comment]
Is v7 needed? I don't remember any issues with v6 🤔 Has anything changed recently?

**Comment by NeOMakinG** [comment]
> Is v7 needed? I don't remember any issues with v6 🤔 Has anything changed recently?

There are some changes inside `package-lock.json`, enforcing the fact that everyone is using v7 while working on develop means that we won't have any conflict on `package-lock.json` files in the future. Also, we really need to follow NodeJS/NPM versions smoothly to avoid any problems in the future by staying updated

**Review by atomiix — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @NeOMakinG

**Comment by eternoendless** [comment]
This has to be backported into 1.7.x right?

**Comment by NeOMakinG** [comment]
@eternoendless already backported here: https://github.com/PrestaShop/docs/pull/1055/files

**Pull request merged**
