### PR TITLE
The list of Smarty variables deserve a title

### PR DESCRIPTION
**Pull request by jf-viguier**
Add a title to the List of Smarty variables.
It's a very frequent google query and this part should be seo optimized.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Add a title to the List of Smarty variables. It's a very frequent google query and this part should be seo optimized.
| Fixed ticket? | none

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @jf-viguier

**Comment by matks** [comment]
Could you maybe backport this to 1.7.x :) ?

**Comment by jf-viguier** [comment]
No, SEO of 8.0 version has to be optimized,

**Comment by matks** [comment]
@jf-viguier We can optimize the SEO of both 1.7.x and 8.x 😄  it's important that people that look for informations about 1.7 find it, and people that look for informations about 8 find it.

**Pull request merged**
