### PR TITLE
Import component docs

### PR DESCRIPTION
**Pull request by rokaszygmantas**
This documentation describes the partly migrated import component.

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
Hello @rokaszygmantas,

who can review this contribution? I haven't followed the contribution(s) in the Core about the Import system.

Maybe @matks?

Mickaël

**Comment by rokaszygmantas** [comment]
Hi @mickaelandrieu, I was the only one working on import so I guess no one (or anyone) :) @matks was reviewing the import PR so maybe he could review this as well.

**Comment by rokaszygmantas** [comment]
@matks thanks for feedback, I'll update the docs accordingly. I can cover the JS part as well, good idea :slightly_smiling_face:

**Comment by rokaszygmantas** [comment]
hi @matks, I've fixed the PR according to your feedback, also explained the javascript part. :slightly_smiling_face:

**Comment by matks** [comment]
@rokaszygmantas Thank you 😄 I think this is quite complete 👍 nice work !

**Pull request merged**
