### PR TITLE
Document removed endpoints

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Document removed endpoints in https://github.com/PrestaShop/PrestaShop/pull/27917
| Fixed ticket? | ~

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @eternoendless

**Comment by matks** [comment]
Argh 😢  I thought it was a "PR doc opened after PR on Core was merged" case when actually PR https://github.com/PrestaShop/PrestaShop/pull/27917 was not merged yet. Sorry.

**Comment by matks** [comment]
PR was merged without changes

**Comment by eternoendless** [comment]
The changes have been merged after all :)

**Pull request merged**
