### PR TITLE
Remove Distributing on Addons in theme export

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Remove Distributing on Addons in theme export
| Fixed ticket? |

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by NeOMakinG — DISMISSED** [review]
A decision needs to be made on the doc before removing this, blocking it until we've some news!

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @jf-viguier

**Comment by eternoendless** [comment]
This should be backported to 1.7.x right?

**Comment by matks** [comment]
@intraordinaire Similarly to https://github.com/PrestaShopCorp/validator/pull/95 this PR removed some information related to selling themes on addons.prestashop.com . Where should this go? on https://validator.prestashop.com/ ? somewhere else?

**Pull request merged**
