### PR TITLE
Improve introduction, move cache section to core/architecture

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Improved the module's introduction article, moved cache part to core/architecture because it had little to do with modules, really.

### CODE REVIEW

**Review by matks — APPROVED** [review]
Do you think it would be useful to add links from Modules introduction page to this new cache page, in order to help module developers that explore the Module section find this page?

I don't know whether module developers read both "Modules" section and "Core reference", I'm afraid some might skip "Core reference" (that might need to be renamed btw) and go straight to "Modules" section, thus missing out some important documentation.

**Comment by eternoendless** [comment]
I think your suggestion is definitely valid, but not in the introduction. This link should probably go in the Extension concepts part. I'm going through the whole documentation right now, I'll be pushing it page by page as separate PRs as I go so it's easier to review and merge quickly.

**Comment by matks** [comment]
> I think your suggestion is definitely valid, but not in the introduction. This link should probably go in the Extension concepts part. I'm going through the whole documentation right now, I'll be pushing it page by page as separate PRs as I go so it's easier to review and merge quickly.

If you go through the whole documentation, I would suggest you try to analyze how you feel about each section. Which ones are big and could be split, which ones are too small. Did you see duplicate content? Did you see 2 topics that should be merged into one ? Did you read, many pages later, some information you wish you were provided 10 minutes before ?

Basically going through the whole documentation should give you the necessary vision to [find a good new structure for the documentation](https://github.com/PrestaShop/docs/issues/241).

**Comment by eternoendless** [comment]
For sure :)

**Review by matks — APPROVED** [review]

**Pull request merged**
