### PR TITLE
Modules: replace "addCSS" and "addJS" by "registerStylesheet" and "registerJavascript"

### PR DESCRIPTION
**Pull request by yannicka**
`addCSS` and `addJS` are deprecated. Instead we should use `registerStylesheet` and `registerJavascript`.

### CODE REVIEW

**Comment by eternoendless** [comment]
Be aware that this works only for `ModuleFrontControllers`. `ModuleAdminControllers` still need `addCSS` and `addJS`.

**Comment by eternoendless** [comment]
@Quetzacoalt91 can you confirm?

**Comment by Quetzacoalt91** [comment]
Indeed, `registerStylesheet` & `registerJavascript` are defined in FrontController, preventing BO controller to access them.

**Comment by matks** [comment]
> Be aware that this works only for `ModuleFrontControllers`. `ModuleAdminControllers` still need `addCSS` and `addJS`.

The modified doc is about front controller so this PR seems valid anyway ?

**Comment by Progi1984** [comment]
Ping @yannicka

**Comment by yannicka** [comment]
We're on a page named "Displaying content on the front office" and the class we create extends `ModuleFrontController`, so I think this PR is fine.

**Comment by Progi1984** [comment]
Thanks @yannicka

**Pull request merged**
