### PR TITLE
Update hugo to 0.82

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | This change updates hugo version and [enables support for css classes after markdown blocks](https://gohugo.io/news/0.81.0-relnotes/#attribute-lists-after-markdown-blocks)

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Please update Github Actions : https://github.com/PrestaShop/docs/blob/master/.github/workflows/build.yml#L29

**Comment by PierreRambaud** [comment]
> Please update Github Actions : https://github.com/PrestaShop/docs/blob/master/.github/workflows/build.yml#L29

We should use the installHugo.sh script instead of a custom github action :thinking:

**Comment by Progi1984** [comment]
We should use a github action and remove the installHugo.sh

**Comment by PierreRambaud** [comment]
> We should use a github action and remove the installHugo.sh

Nope because we also need to be able to download the same hugo version without having to fetch the whole internet. We are not able to use `go dep`, and only the binary file is needed.

**Comment by eternoendless** [comment]
Fixed GA on master branch

**Comment by matks** [comment]
> > Please update Github Actions : https://github.com/PrestaShop/docs/blob/master/.github/workflows/build.yml#L29
> 
> We should use the installHugo.sh script instead of a custom github action 🤔

I approve ⬆️ 

Just struggled because I had hugo v0.80 😅

**Pull request merged**
