### PR TITLE
Add MySQL MariaDB requirements

### PR DESCRIPTION
**Pull request by nicohery**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Answer to issues installing or upgrading Prestashop 1.7.7 using MySQL < 5.7 or MariaDB < 10.2. I suggest add database requirements with a beautiful chart as like as PHP one.
| Fixed ticket? | Answer #22809 #22960 and #21948 related issues

### CODE REVIEW

**Comment by matks** [comment]
@PierreRambaud I think you'll know better than me 😅

**Comment by PierreRambaud** [comment]
Hi,

There is an issue related to it, we have to reproduce the error with a MySQL 5.6 installation, if it can be bypass by a configuration, MySQL is still compatible but need adjustement, otherwise we can approve this pull request. :)

**Comment by nicohery** [comment]
Yes, you can bypass it through a MySQL configuration. **[https://community.pivotal.io/s/article/Apps-are-down-due-to-the-Maximum-Column-Size-is-767-bytes-Constraint-in-MySQL?language=en_US](https://community.pivotal.io/s/article/Apps-are-down-due-to-the-Maximum-Column-Size-is-767-bytes-Constraint-in-MySQL?language=en_US)**
But this workaround must be specified in the requirements.
In my opinion, Prestashop should be installable on PHP MySQL "default" installation. Not all "users" have MySQL permissions or knowledge to change this configuration.

**Review by atomiix — APPROVED** [review]

**Comment by PierreRambaud** [comment]
> Yes, you can bypass it through a MySQL configuration. **https://community.pivotal.io/s/article/Apps-are-down-due-to-the-Maximum-Column-Size-is-767-bytes-Constraint-in-MySQL?language=en_US**
> But this workaround must be specified in the requirements.
> In my opinion, Prestashop should be installable on PHP MySQL "default" installation. Not all "users" have MySQL permissions or knowledge to change this configuration.

I disagree with it. It's like PHP, PrestaShop is not working with the default PHP installation, a lot of extensions are required, and not all PHP users have permissions or knowledge to change this configuration :wink:

**Review by sowbiba — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]
@PierreRambaud do you disapprove this PR ?

**Comment by PierreRambaud** [comment]
> @PierreRambaud do you disapprove this PR ?

Yes, PrestaShop is still compatible with MySQL 5.6 :thinking:

**Review by matks — CHANGES_REQUESTED** [review]
Agreed with @PierreRambaud 

Provided I configure it properly, I can run PrestaShop 1.7.7 using MySQL 5.6 . So PrestaShop 1.7.7 is compatible with MySQL 5.6 .

**Comment by matks** [comment]
> Yes, you can bypass it through a MySQL configuration. **https://community.pivotal.io/s/article/Apps-are-down-due-to-the-Maximum-Column-Size-is-767-bytes-Constraint-in-MySQL?language=en_US**
> But this workaround must be specified in the requirements.

We can document this workaround in the doc 😉 

Maybe in "requirements" page? Or in FAQ ?

**Comment by nicohery** [comment]
You're right, my proposal was too strict ! A workaround instruction in the doc is enough (but necessary).

**Comment by matks** [comment]
Hi, I close this PR as this PR will not be merged (if I understood correctly).

Do you plan to open another PR for

> A workaround instruction in the doc is enough (but necessary).

or should I do it?

**Pull request closed without merging**
