### PR TITLE
Add some useful resources to deal with PRs

### PR DESCRIPTION
**Pull request by ttoine**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

### CODE REVIEW

**Comment by matks** [comment]
Thank you @ttoine

**Comment by matks** [comment]
@ttoine also it's nice to see you used your fork 😊  well done ! 👏

**Comment by ttoine** [comment]
As I already told many times, it's of course ok to use a fork when it's not about the blog content 😎
I only hope that one day, GitHub will allow to update the fork with a single click on a button on the web UI.

**Comment by matks** [comment]
> As I already told many times, it's of course ok to use a fork when it's not about the blog content 😎
> I only hope that one day, GitHub will allow to update the fork with a single click on a button on the web UI.

ping @github 😄

**Pull request merged**
