### PR TITLE
Documented BC for PR #27890 (core repository)

### PR DESCRIPTION
**Pull request by marsaldev**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Add documentation for a new BC through this PR https://github.com/PrestaShop/PrestaShop/pull/27890
| Fixed ticket? | ~

### CODE REVIEW

**Comment by marsaldev** [comment]
ping @Progi1984

**Review by kpodemski — CHANGES_REQUESTED** [review]
Waiting for related PR to be merged

**Comment by kpodemski** [comment]
@marsaldev thanks, I'm blocking this to not allow anyone to merge before PR :D

**Comment by marsaldev** [comment]
We can unblock this PR? thanks 😊

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Thanks @marsaldev

**Comment by Progi1984** [comment]
@kpodemski :warning: The BC Break has been added to `8.0.0` version. But the PR has been merged in `develop` branch so for the `8.1` version.

**Comment by kpodemski** [comment]
@Progi1984  you are right, I'll revert it :) I thought this one supposed to go to the v8 🤔

**Pull request merged**
