### PR TITLE
Wrap bash command in bash block

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Wrap bash command in bash block to keep consistency throughout the page and to avoid long command overflow in mobile view.
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
@leemyongpakvn on fire these days 🐐

**Comment by NeOMakinG** [comment]
@leemyongpakvn did you backport it to 1.7? I'm thinking about adding a backport link field in the PR template

**Comment by leemyongpakvn** [comment]
@NeOMakinG Backported to 1.7. I'd prefer rain and leaf :evergreen_tree:. A backport link will be  useful but I don't know how to do it.

**Review by ghost — APPROVED** [review]

**Comment by NeOMakinG** [comment]
> @NeOMakinG Backported to 1.7. I'd prefer rain and leaf 🌲. A backport link will be useful but I don't know how to do it.

We need to change the pull request template on the main branch of the repository and add a `Backport link?` section, if you want to do it, feel free :)

**Pull request merged**
