### PR TITLE
Add list of native modules

### LINKED ISSUE #459: List all the native modules
List all native modules with name, technical name, short description, preinstalled yes/no, link to Github and PS version on which they were included.

Related to https://github.com/PrestaShop/open-source/issues/16

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Added a list of all native modules
| Fixed ticket? | Fixes #459

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
What do you think about moving the relation between 1.6 and 1.7 modules in this part ? https://devdocs.prestashop.com/1.7/modules/introduction/#main-differences-between-16-and-17-modules

**Comment by eternoendless** [comment]
Excellent idea

**Comment by eternoendless** [comment]
Done @Quetzacoalt91

**Comment by Quetzacoalt91** [comment]
Looks like you have a conflict to solve before merging the PR

**Pull request merged**
