### PR TITLE
Fix Minor typos in the documentation in update CI/CD

### PR DESCRIPTION
**Pull request by Om3n31**
Minor typos

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | Minor typos in the documentation
| Fixed ticket? |

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Cool ! thanks @Om3n31

**Comment by matks** [comment]
@Om3n31 would you consider submitting a PR for branch `8.x` as well?

**Comment by Om3n31** [comment]
> @Om3n31 would you consider submitting a PR for branch `8.x` as well?

Done, 
I have some questions about CI/CD with Prestashop, is there any way that you could lend me some of your time to answer them ? I'll try to be very concise. (I understand if you're too busy though)

**Comment by matks** [comment]
> I have some questions about CI/CD with Prestashop, is there any way that you could lend me some of your time to answer them ? I'll try to be very concise. (I understand if you're too busy though)

Come to chat with the team on Slack 😄  https://www.prestashop-project.org/slack/

**Pull request merged**
