### PR TITLE
Using prestashop-project.org links instead of prestashop.com

### PR DESCRIPTION
**Pull request by sarahdib**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Using prestashop-project.org links instead of prestashop.com
| Fixed ticket? | no

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by thomasnares — APPROVED** [review]

**Comment by thomasnares** [comment]
Thanks @sarahdib, could you backport it on 1.7 ?

**Comment by sarahdib** [comment]
> Thanks @sarahdib, could you backport it on 1.7 ?

I don't know how it works on this repo, do you merge 1.7.x into 8.x ? or the backport should be independent ?

**Comment by thomasnares** [comment]
Ok, you have to checkout on the 1.7 branch, then you do : 

`git cherry-pick _list of commit ids to pick_`

then you create a new PR on 1.7

**Comment by sarahdib** [comment]
done #1566

**Pull request merged**
