### PR TITLE
Upgrade files are now in autoupgrade module

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Files are now in the autoupgrade modules and are going to be removed from the core

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @PierreRambaud

**Comment by matks** [comment]
@PierreRambaud Should we backport this PR or not? 🤔  does it make sense for 1.7 doc ?

**Comment by PierreRambaud** [comment]
> @PierreRambaud Should we backport this PR or not? thinking does it make sense for 1.7 doc ?

I think yes :thinking: even if we remove scripts only for the 8.0, we will now handle SQL and php scripts in the next version of the autoupgrade module

**Comment by matks** [comment]
We will have to make sure people understand that
- in PS < 8.0.0 there is SQL scripts inside the Core, for all 1.7 versions
- the autoupgrade module < 5.0.0 use these scripts inside the Core
- the autoupgrade module 5.0.0 use its own scripts

**Pull request merged**
