### PR TITLE
Update translation domains page

### PR DESCRIPTION
**Pull request by Julievrz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | Update translation domains page

### CODE REVIEW

**Comment by Julievrz** [comment]
I wanted to do embeds but I don't know how to do it. Also I don't know how to add a "Download" button to download the files.

**Comment by matks** [comment]
@Julievrz What do you want to embed? The google drive files like https://drive.google.com/file/d/1xx9hVLrAEgUVw9PNSOw3DkI5tUdeH6wK/preview ?

I'm not sure if we can embed files inside the devdocs but maybe we could screenshot them and people click on the link to reach it?

Also: I don't think it's good to link to files stored inside Google Drive because if you close your account they might disappear. Can we store them inside this doc? I can help you to upload them.

**Comment by Julievrz** [comment]
> @Julievrz What do you want to embed? The google drive files like https://drive.google.com/file/d/1xx9hVLrAEgUVw9PNSOw3DkI5tUdeH6wK/preview ?
> 
> I'm not sure if we can embed files inside the devdocs but maybe we could screenshot them and people click on the link to reach it?
> 
> Also: I don't think it's good to link to files stored inside Google Drive because if you close your account they might disappear. Can we store them inside this doc? I can help you to upload them.

I wanted to embed the whimsical links: 

https://whimsical.com/shop-XHbGRCKs7fd9JCcxasZAmw
https://whimsical.com/admin-RMLMzSvFzpXV4NafgjRhe2
https://whimsical.com/modules-tJrNFcB632iozEvtz6ncj
https://whimsical.com/emails-UC37xojRrrqXTpa81UtzdE

And two documents. Yes I can send the documents to you, thanks!

**Comment by Julievrz** [comment]
Thank you for your help @matks

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @Julievrz

**Comment by matks** [comment]
Backported in 8.x in https://github.com/PrestaShop/docs/pull/1312

**Pull request merged**
