### PR TITLE
Fix paths for `ref` and `relref` shortcodes to have anchors in generated html-files.

### LINKED ISSUE #692: Links generated without anchors.
When I make pull-request #691 I found that anchors in links not generated, when path ends with `.md`. If path without extension, then links generated with anchors.

I don't now if it's hugo's bug or not. But seems that it would be better to remove `.md` extension for all links paths in documentation.

## Example page with link's path ends with `.md` and not contains anchor in generated url
https://devdocs.prestashop.com/1.7/development/components/grid/bulk-actions-reference/ - at the bottom "covered link".

image

But anchor [exists in source](https://github.com/PrestaShop/docs/blob/master/src/content/1.7/development/components/grid/bulk-actions-reference/_index.md):
image

## Example page with link''s path not ends with `.md` and contains anchor in generated url
https://devdocs.prestashop.com/1.7/development/components/grid/tutorials/work-with-search-form/#reset-action- after "Reset action" header see "SearchAndResetType options"-link.

image

Contains [rel path without `md`](https://github.com/PrestaShop/docs/blob/master/src/content/1.7/development/components/grid/tutorials/work-with-search-form/_index.md):
image

### PR DESCRIPTION
**Pull request by likemusic**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fix paths for `ref` and `relref` shortcodes to have anchors in generated html-files.
| Fixed ticket? | Fixes #692 

This PR includes:
- remove `.md` ends in all `ref` and `relref` paths;
- paths ends `/_index.md` replaces to just `/` (because paths ending `/_index` generates error `REF_NOT_FOUND`);

This PR doesn't introduce any new broken links. To check this I scan devdoc in master and this PR branches by [Xenu](http://home.snafu.de/tilman/xenulink.html). There is scan results screenshots:

- for this PR branch:
image

- for master-branch:
image

Xenu scan result files in attaches:
[links-anchors.zip](https://github.com/PrestaShop/docs/files/5147342/links-anchors.zip)
[master.zip](https://github.com/PrestaShop/docs/files/5147343/master.zip)

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Comment by Progi1984** [comment]
@PierreRambaud I'm not sure with this PR. What do you think about it ?

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
> @PierreRambaud I'm not sure with this PR. What do you think about it ?

It's ok regarding https://gohugo.io/content-management/cross-references/

**Comment by Progi1984** [comment]
Thanks ;) @PierreRambaud

**Comment by NeOMakinG** [comment]
Thanks @likemusic

**Pull request merged**
