### PR TITLE
Add notes that db account with full privileges have to be used

### PR DESCRIPTION
**Pull request by Mirgen**
Due to my personal experiences with upgrades on some web providers I find it nice to remind others that this can happen.

### CODE REVIEW

**Comment by matks** [comment]
Interesting 🤔 thanks for the feedback ! So I guess the 2nd database account had only READ/WRITE access but could not create or update the SQL schema ?

**Comment by Mirgen** [comment]
Exactly. It is obviously for security reasons. The bigggest web provider Wedos in Czech Republic have it like this.

**Comment by matks** [comment]
Thank you @Mirgen

**Comment by Mirgen** [comment]
@matks  BTW I am amazed how fast it was with your reply and merge 👍

**Comment by matks** [comment]
@Mirgen Thanks 😄

**Pull request merged**
