### PR TITLE
Fix Position location

### PR DESCRIPTION
**Pull request by TheDreamCatcher**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | The position page is inside the Design one, not inside the Modules part

### CODE REVIEW

**Comment by SharakPL** [comment]
Yeah, that has always confused me. If it's about modules, then why is it suddenly in Design section and not in Modules section, where it was in Prestashop 1.6?

**Comment by kpodemski** [comment]
Because hooks that you can sort are more likely to be used on the front office (Design of the store)

**Comment by SharakPL** [comment]
1. You can't sort hooks. To do that you need to change their placement in .tpl files. You can sort modules inside specific hook, so again: it's about modules more than about design.
2. Both front office and back office use the same page for changing **modules' positions** 😉 These last 2 words are self-explanatory, Design -> Positions is not that obvious.

At least it should be changed to _Design -> Modules' position_ or _Design -> Hooks_

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @TheDreamCatcher 

@SharakPL if you want to challenge the position in the menu, you will have to talk to @PrestaShop/product-team on https://github.com/prestashop/prestashop 😉

**Comment by SharakPL** [comment]
Thanks @matks

**Comment by matks** [comment]
PR to update 8 branch https://github.com/PrestaShop/docs/pull/1158

**Pull request merged**
