### PR TITLE
Delete the migration guide from 1.6

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Maybe we should leave a single link saying "Hello, if you're looking for the doc 'how to migrate from 1.6 to 1.7' please look there?

**Review by matthieu-rolland — COMMENTED** [review]
thank you for the PR @PrestaEdit , I agree with @matks about the link

**Review by matks — CHANGES_REQUESTED** [review]
Please see above feedback

**Review by kpodemski — COMMENTED** [review]
Hey @PrestaEdit 👋 

Could you bring back this page and simply link to the 1.7 documentation?

**Comment by leemyongpakvn** [comment]
I suggest "Please read 'how to migrate from 1.6 to 1.7' then come back here later."

**Comment by matks** [comment]
Hi,

Since we had no news from you for more than 30 days, I will follow [our guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/#stale-pull-requests) and I'll close this pull request as it seems stale. Feel free to reopen or open another one if you think it's still relevant.

Thanks!

**Pull request closed without merging**
