### PR TITLE
Update create user SQL query

### PR DESCRIPTION
**Pull request by shef-er**
IDENTIFIED BY cannot be used in GRANT request

### CODE REVIEW

**Comment by matks** [comment]
Maybe it's some specific database engines or versions ? Because I can see plenty of examples on google using IDENTIFIED with GRANT BY
https://mediatemple.net/community/products/dv/204404494/how-do-i-grant-privileges-in-mysql

Anyway I like the idea of splitting the queries as it makes the example clearer for people (each step does one thing, no mix)

**Comment by shef-er** [comment]
Ok, maybe there is some databases that allows to do such request. I ran the original line in the mysql 8.0.20 and had recived  syntax error

**Comment by shef-er** [comment]
Also there is no IDENTIFIED BY with GRANT request in the official documantation https://dev.mysql.com/doc/refman/8.0/en/grant.html for MySQL

**Comment by PierreRambaud** [comment]
Thanks @shef-er

**Pull request merged**
