### PR TITLE
Fix missing grid's namespaces example

### PR DESCRIPTION
**Pull request by PrestaSafe**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | Load 2 missing namspace for avoiding error messages

### CODE REVIEW

**Review by PrestaEdit — APPROVED** [review]

**Review by jf-viguier — APPROVED** [review]

**Comment by jf-viguier** [comment]
1.7 branch, should be ported to 8.0 branch too

**Review by NeOMakinG — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @PrestaSafe do you think you can backport changes to branch 8.0.x?

**Comment by PrestaSafe** [comment]
@matks it’s already done here https://github.com/PrestaShop/docs/pull/1404 ;)

**Comment by thomasnares** [comment]
@kpodemski please remove tag needs backport, already done

**Pull request merged**
