### PR TITLE
Update nginx.md

### PR DESCRIPTION
**Pull request by yildizib**
without this line nginx seo url not working.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

### CODE REVIEW

**Comment by matks** [comment]
Hello, thanks for the contribution

By "SEO URL" do you mean customizable URL patterns that you can edit from Back-Office?

**Comment by matks** [comment]
Hello @yildizib as I get no answer, I close the PR.

If you come back 😉  please ping me I will reopen the Pull Request.

Thank you for your contribution

**Comment by lukasz-zaroda** [comment]
@matks I confirm that current nginx configuration just doesn't work, and adding the mentioned line fixes the issue. The issue is that without this fix, all pages addressed by "pretty urls" result in 404.

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @yildizib

**Pull request merged**
