### PR TITLE
Fix wrong directory in CI when in pull request

### PR DESCRIPTION
**Pull request by eternoendless**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Fixed the directory used in CI when building for pull requests. Only push was working because github.ref is the name of the branch being buiolt, not the destination branch.
| Fixed ticket? | N/A

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Bash script is not the most readable we can do ^^

Would it be overkill to put this bash script in a file in `.github` and a test to it? This stuff is fragile and is easy to break if we modify it later

**Review by PierreRambaud — APPROVED** [review]

**Comment by eternoendless** [comment]
This is not a bash script @matks although it does have some bash in it. I don't understand what you have in mind actually.

> This stuff is fragile and is easy to break if we modify it later

Let's try not to modify it then 😛

**Comment by matks** [comment]
> This is not a bash script @matks although it does have some bash in it. I don't understand what you have in mind actually.

I was meaning these parts:
```
echo $TARGET_BRANCH | perl -pe 's|^([\d.]+)(?:\.x)?$|\1|'
```

```
          VERSION_FORMAT='^([0-9]+\.)*[0-9]+$'
          if [[ ! $VERSION =~ $VERSION_FORMAT ]]; then
            echo "::error::Version '$VERSION' is not a valid version!"
            exit 1
          else
            echo "Version: '$VERSION'"
          fi
```

**Review by matks — APPROVED** [review]

**Comment by eternoendless** [comment]
Merging to unblock CI, but discussion can continue

**Pull request merged**
