### PR TITLE
Remove note about display parameter

### PR DESCRIPTION
**Pull request by PrestaEdit**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | You can use the display onto a specific ressource ; you doesn't need to be on a listing. This call will show you only name of first customer: api/customers/1?display=[lastname]

### CODE REVIEW

**Comment by kpodemski** [comment]
I've tested it on 1.7.7 and it doesn't work as described. Screenshot:

https://www.dropbox.com/s/wt9ao1zuwluiyuz/Zrzut%20ekranu%202022-02-18%20o%2020.16.22.png?dl=0

**Review by matks — COMMENTED** [review]
Maybe I'm wrong but, if I read this sentence, I think it means

"If you want to read the records of customers 28, 92 and 98 but you only want firstname and email for them you need to use `display` to get only firstnames and emails and `filter` to only get customers 28, 92 and 98"

So this sentence seems OK for me 🤔 ?

**Review by matks — COMMENTED** [review]
Friendly reminder @PrestaEdit 😄

**Review by matks — CHANGES_REQUESTED** [review]
Waiting for feedback after kpodemski review

**Comment by matks** [comment]
Hello, it seems this PR is now stale.

I close this PR, following our [review guidelines](https://devdocs.prestashop.com/1.7/project/maintainers-guide/reviewing-pull-requests/) "Pull Requests may be closed after 30 days of inactivity". If however you are still interested in it, please ping us :) we can reopen.

Thank you for your contribution.

**Pull request closed without merging**
