### PR TITLE
Typo fixes.

### PR DESCRIPTION
**Pull request by xBorderie**

### CODE REVIEW

**Comment by xBorderie** [comment]
Also: "If you want to use Stylus or Less, simply edit the command line under the "scripts" section".
There is no "scripts" section below :)

**Comment by julienbourdeau** [comment]
Oops, the sentence has to be removed. Stylus and Less work out of the box :sunglasses:

**Comment by julienbourdeau** [comment]
Thank you for editing!

**Comment by xBorderie** [comment]
> Stylus and Less work out of the box

Wow, nice! :)

**Pull request merged**
