### PR TITLE
change php version for 9

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 9
| Description?  | php version
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

### CODE REVIEW

**Comment by kpodemski** [comment]
@PrestaEdit was faster this time Jeff :)

**Comment by jf-viguier** [comment]
@kpodemski ideed ! 
I've set the recommanded version to php 8.3, @PrestaEdit 8.1, were is the truth ?

**Comment by PrestaEdit** [comment]
On my own, I will suggest the 8.1 as the support of the two others versions are added after.
Also, the latest 1.7.8.x are made to support the 8.1 at maximum. It will be a good interesection.

**Comment by kpodemski** [comment]
@jf-viguier @PrestaEdit 

I don't like such recommendations, it all depends on various factors and common sense would tell that the best is the recent version, but my personal opinion is similar to yours, Jonathan. I think it would be wiser to expect ecosystem to support PHP 8.1, PHP 8.2 and 8.3 may require some extra effort.

**Pull request closed without merging**
