### PR TITLE
Wrong link to 1.6 versions

### PR DESCRIPTION
**Pull request by okom3pom**
Is this paragraph useful here?

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Is this paragraph useful here?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Comment by matks** [comment]
I think the link `https://www.prestashop.com/en/previous-versions?version=1.6` is broken. It's the right link but it now redirects to a bad page.

For example it's used here https://www.prestashop.com/en/prestashop-1-6

I will reach out to the team in charge of prestashop.com for fix 😉

**Review by PierreRambaud — CHANGES_REQUESTED** [review]
The link is logically right, see @matks' comment :) 
But keep the PR open in case of the team in charge of prestashop.com says everything is ok :sweat_smile:

**Comment by Progi1984** [comment]
@matks Some news ?

**Comment by matks** [comment]
@Progi1984 I screamed in the void and the void did not answer 😭

**Comment by okom3pom** [comment]
```
The link is logically right, see @matks' comment :)
But keep the PR open in case of the team in charge of prestashop.com says everything is ok sweat_smile
```

@PierreRambaud  visionary

**Comment by okom3pom** [comment]
The sorting is very strange I think with this screenshot the team in charge of prestashop.com will have to move

Haha last version beta 2 after beta 1 after RC :D 

Capture d’écran de 2020-11-05 15-34-54

**Comment by matks** [comment]
> The sorting is very strange I think with this screenshot the team in charge of prestashop.com will have to move
> 
> Haha last version beta 2 after beta 1 after RC :D
> 
> Capture d’écran de 2020-11-05 15-34-54

Yes, this is a 2nd issue that we also reported.

It's in the pipe 👀

**Review by sowbiba — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by PierreRambaud** [comment]
I still convince this PR should be merged and the problem came from the prestashop.com website :thinking:

**Comment by matks** [comment]
> > The sorting is very strange I think with this screenshot the team in charge of prestashop.com will have to move
> > Haha last version beta 2 after beta 1 after RC :D
> > Capture d’écran de 2020-11-05 15-34-54
> 
> Yes, this is a 2nd issue that we also reported.
> 
> It's in the pipe 👀

@okom3pom this one is fixed 😁  but https://www.prestashop.com/en/previous-versions?version=1.6 is not fixed yet

**Comment by matks** [comment]
Should be fixed soon on prestashop.com

**Comment by PierreRambaud** [comment]
Since the issue will be fixed directly on prestashop.com I see no reason to keep this pull request open.

**Comment by matks** [comment]
https://www.prestashop.com/en/previous-versions?version=1.6 has been fixed 😄 

Thank you @okom3pom for reporting the issue

**Pull request closed without merging**
