### PR TITLE
Initial form value improvement

### PR DESCRIPTION
**Pull request by jf-viguier**
Initial form value should come from request (you've just submited the form) or from configuration.

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi @jf-viguier 

Shall we update the reminder as well? There is another occurence l.276.

**Comment by jf-viguier** [comment]
@Quetzacoalt91 done

**Comment by Quetzacoalt91** [comment]
Thank you @jf-viguier

**Comment by jf-viguier** [comment]
Thanks @Quetzacoalt91 for this quick merge 👍 on a closed day

**Pull request merged**
