### PR TITLE
Updating context of where code goes

### PR DESCRIPTION
**Pull request by Wrenbjor**
It's not clear that we are still working with the mymodule.php file because the code block starts with a new <?php block which tricked me into thinking that we were in a new file. I added a line to make sure it's known to work in the mymodule.php file.

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

### CODE REVIEW

**Review by matks — APPROVED** [review]
Thank you this is a nice improvement that makes documentation less confusing 👍

**Review by PululuK — APPROVED** [review]

**Comment by PululuK** [comment]
Thanks @Wrenbjor

**Comment by matks** [comment]
@Wrenbjor Could you submit another PR to update the 8.x branch with your improvement? 😉

**Comment by Wrenbjor** [comment]
@matks please see #1198

**Pull request merged**
