### PR TITLE
getting-started.md grammar mistake corrected  

### PR DESCRIPTION
**Pull request by ThanasisMpalatsoukas**
Small grammar mistake spotted on multiple instances Exemple -> Example

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.x / 8.x
| Description?  | Please be specific when describing the PR. What did you add, why did you submit it?
| Fixed ticket? | Fixes #{issue number here} if there is a related issue

### CODE REVIEW

**Comment by thomasnares** [comment]
Thanks @ThanasisMpalatsoukas 👍

**Review by thomasnares — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
Thank you @ThanasisMpalatsoukas

**Comment by thomasnares** [comment]
Already fixed in 8.x, no backport needed

**Comment by ThanasisMpalatsoukas** [comment]
@kpodemski  @thomasnares Glad i could help!

**Pull request merged**
