### PR TITLE
Add Known Limit about images url rewriting

### PR DESCRIPTION
**Pull request by okom3pom**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add Known limit for images
| Fixed ticket? | Relative to PrestaShop/PrestaShop#21196

### CODE REVIEW

**Comment by okom3pom** [comment]
https://github.com/PrestaShop/PrestaShop/pull/21196

**Comment by okom3pom** [comment]
I close it ? @Progi1984  && @matks ?

**Comment by matks** [comment]
Hi ! I dont think this should go in "system requirements" because this is not a system requirement. People browsing this page are looking for "what do I need to run PrestaShop", not known limitations of the software for really big catalogs.

This looks like an accurate answer to an accurate question so I suggest to move it into the [FAQ section](https://devdocs.prestashop.com/1.7/faq/).

It could be for example:

**Question**

Why can I not use more than 9 999 999 images?

**Answer**

The limitation of the `.htaccess` file prevent the use of more than 9 999 999 images because ...

You can remove this limitation by adding the needed rules to go further. Example ...

**Comment by okom3pom** [comment]
I will move in the FAQ

**Comment by okom3pom** [comment]
https://github.com/PrestaShop/docs/pull/928

**Pull request closed without merging**
