### PR TITLE
Fix docker-compose file to build Hugo container

### PR DESCRIPTION
**Pull request by boubkerbribri**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fix docker-compose file to build Hugo container
| Fixed ticket? | no
| How to test? | 1. Install docker-compose v1.27.1 <br>2. Run `docker-compose up --build --force-recreate`<br> 3.Navigate through docs on `http://localhost:1313/`

### CODE REVIEW

**Comment by matks** [comment]
```
build
GitHub Actions has encountered an internal error when running your job.
```

😅

**Comment by matks** [comment]
Outage on GitHub Actions

**Review by matks — APPROVED** [review]
Seems OK but needs to be tested

**Comment by PierreRambaud** [comment]
Everything is ok! Thank you @boubkerbribri

**Pull request merged**
