### PR TITLE
Grid component and extensions

### PR DESCRIPTION
**Pull request by kpodemski**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add docs about Grid js
| Fixed ticket? | Fixes #{issue number here} if there is a related issue
| Sponsor company | impSolutions

### CODE REVIEW

**Review by matks — APPROVED** [review]
Great !

@zuk3975 @jolelievre @JevgenijVisockij Did I dream? I think I remember we wanted to do this and/or submitted a PR for this but I cannot find it. Just want to make sure @kpodemski PR has no duplicate

**Comment by JevgenijVisockij** [comment]
> Great !
> 
> @zuk3975 @jolelievre @JevgenijVisockij Did I dream? I think I remember we wanted to do this and/or submitted a PR for this but I cannot find it. Just want to make sure @kpodemski PR has no duplicate

You mean this one https://github.com/PrestaShop/docs/pull/1006
I added list of components for form, but I don't think I did anything with the grid. 

In fact I didn't realise we were getting grid components with 1.7.8 as well.

**Comment by zuk3975** [comment]
@matks I think its not duplicating :thinking:. @kpodemski is documenting the usage of recently added global components, which wasn't usable before.
Though maybe its worth linking these here https://github.com/PrestaShop/docs/pull/985/files#diff-daff20484438eaf7a14c9cd3f0bf37af0870dd64957134d015014c140ef07325R309

**Review by NeOMakinG — APPROVED** [review]
Looks fine to me :)

Love the fact that almost all our components are accessible globally and easily

**Comment by matks** [comment]
Thank you @kpodemski

**Pull request merged**
