### PR TITLE
Document configuration console command

### PR DESCRIPTION
**Pull request by tswfi**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | develop
| Description?  | Add documentation about configuration console command
| Fixed ticket? | 

This should only be merged after https://github.com/PrestaShop/PrestaShop/pull/26183 is merged and the minver number should be double checked at that moment also.

### CODE REVIEW

**Comment by tswfi** [comment]
No branch for 1.8.x?

**Comment by matks** [comment]
It's 8.x ;) not 1.8.x

**Comment by eternoendless** [comment]
This will have to be rebased into `8.x` as the PR targets develop. Let's wait until the PR is merged before though.

**Review by Progi1984 — DISMISSED** [review]
Need that the relative PR be merged

**Review by eternoendless — CHANGES_REQUESTED** [review]
The change has been merged, this now needs to be rebase into the appropriate branch

**Comment by tswfi** [comment]
yeah, so rebase started to look way too much work. made a new pr for this #1252

**Pull request closed without merging**
