### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by Arman-Hosseini**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | `8.x`
| Description?  | `Fix broken links`
| Fixed ticket? | `N/A`

### CODE REVIEW

**Review by Arman-Hosseini — COMMENTED** [review]
Same : https://github.com/PrestaShop/docs/blob/7bfc55733b50b8fd0ad4d976755493c4285d9f1b/modules/sample-modules/order-pages-new-hooks/_index.md
I'm not sure if the markdown is valid or not, but I guess it must be fixed from another source.

**Review by ghost — COMMENTED** [review]
Hello @Arman-Hosseini 

Nice catch 

I think you can use something like this : 

`({{< relref "/8/modules/sample-modules/order-pages-new-hooks" >}})`

`<` and `>` missing

**Comment by Arman-Hosseini** [comment]
Thanks. I'll do this for all the missed ones.

**Comment by leemyongpakvn** [comment]
I'm quite sure that you just need one more slash like this ```/```8/basics/installation/system-requirements/#php-compatibility-chart

**Comment by kpodemski** [comment]
Hi @Arman-Hosseini 

Any news on your side? : >

**Comment by kpodemski** [comment]
I'm closing this PR in favor of https://github.com/PrestaShop/docs/pull/1470/files

Thank you for your contribution anyway, appreciate it!

**Pull request closed without merging**
