### PR TITLE
New hook list / page with improved search

### PR DESCRIPTION
**Pull request by thomasnares**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | New hook page, with improved search, and use-case examples capabilities

Must be merged with : https://github.com/PrestaShop/ps-docs-theme/pull/14
Then, we must quickly backport this feature into doc of 1.7 (search for hook broken if new theme deployed)

### CODE REVIEW

**Comment by thomasnares** [comment]
@kpodemski Re-opened a fresh one, broke my previous branch when rebasing 😱

**Comment by thomasnares** [comment]
Build failed because of the missing shortcode https://github.com/PrestaShop/ps-docs-theme/pull/14

**Comment by kpodemski** [comment]
@thomasnares yep, no worries, I understand

what I'm not sure about is the part about backporting things. Maybe you could have this new search conditionally? The hook list is different. I'm afraid there will be too much work to have it in 1.7, but let me know

**Comment by thomasnares** [comment]
> @thomasnares yep, no worries, I understand
> 
> what I'm not sure about is the part about backporting things. Maybe you could have this new search conditionally? The hook list is different. I'm afraid there will be too much work to have it in 1.7, but let me know

Yes sure, i can make the search work for both 1.7 and 8, let me do that

**Comment by thomasnares** [comment]
After some internal review, i made some little changes : 

- change "hook type" (display/action) from array to single value since the type can never be both
- keep location (front office / back office) to array since they can be both (ObjectModel ones for example)
- change < to &lt; in hook names for display
- change backoffice/frontoffice to back office and front office 
- change search tip on index since we implemented a regex based search for generic hooks (see https://github.com/PrestaShop/ps-docs-theme/pull/15 ) 🚀

**Review by kpodemski — APPROVED** [review]
Ok, let's see this live! Well done, @thomasnares 👏 !

**Pull request merged**
