### PR TITLE
Improved behat docs for new optimizations

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | Add docs about behat test and how to use new features for database restoration, cache clearing and kernel reboot
| Fixed ticket? | ~

### CODE REVIEW

**Review by matks — APPROVED** [review]
@jolelievre thanks ! this doc is great

but you need to rebase before we can deploy it

**Review by matthieu-rolland — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @matks and @matthieu-rolland 
I just rebased the PR

**Comment by jolelievre** [comment]
Hmm, force push doesn't stale the approved reviews...
Maybe we should configure this repo more strictly?

**Comment by matthieu-rolland** [comment]
thanx @jolelievre !

**Pull request merged**
