### PR TITLE
Fix release lifecycle links

### PR DESCRIPTION
**Pull request by matks**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 8.x
| Description?  | I noticed the link on page "Patch release lifecycle" targets the blog "Minor release lifecycle" and the link on page "Minor release lifecycle" targets the blog "Patch release lifecycle". It's inversed.
| Fixed ticket? |

### CODE REVIEW

**Review by thomasnares — APPROVED** [review]

**Comment by thomasnares** [comment]
Thanks @matks

**Comment by kpodemski** [comment]
@thomasnares maybe you could rebase using @matks branch to resolve conflicts?

**Comment by thomasnares** [comment]
@kpodemski since it was fixed here : https://github.com/PrestaShop/docs/commit/5c033616ddfaa8b332d937bd6c79178c203b29c7

Should we rebase something ?

**Comment by kpodemski** [comment]
@thomasnares I didn't notice this change. No, in that case, we can safely close this PR.

**Pull request closed without merging**
